// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trophy } from "./Trophy";

export interface TrophyCase {
  trophies: Array<Trophy> | null;
}
